- name: 'install apt db packages'
  apt: pkg="{{item}}" state=present
  with_items:
    - zsh
    - tree
    - mysql-client-5.6
    - libmysqld-dev
    - imagemagick

- name: Install Bundler
  sudo_user: root
  command: bash -lc "/usr/local/rbenv/shims/gem install bundler && /usr/local/rbenv/bin/rbenv rehash"

- name: 'create rails app dir'
  file: path=/var/www state=directory owner=aroma group=aroma mode=0755
