- name: 'install apt db packages'
  apt: pkg="{{item}}" state=present
  with_items:
    - emacs24-nox

- name: add .ssh/config
  template: src=../files/ssh_config dest=/home/{{ item }}/.ssh/config owner={{ item }} group=users mode=644
  with_items:
    - yoshinbo
